# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Register Schema

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.*'
    - name: Install dependencies
      run: |
        sudo apt-get install python3
        sudo apt-get install -y python3-pip
        sudo apt install python-confluent-kafka
        sudo pip3 install confluent-kafka
    - name: start app
      run: |
        python3 ./action/app.py

